name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v4

      - uses: tooppoo/rellog/actions/ready@v0.0.5
        with:
          release-id: ${{ github.ref_name }}

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: 'go.mod'

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Check
        run: just ci

      - name: Save licenses
        run: just license-save

      - name: create VERSION file
        run: echo ${{ github.ref_name }} > VERSION

      - name: craete release note file as input
        run: |
          cat .rellog/release-notes/${{ github.ref_name }}.md \
            | grep -v "^## " \
            > tmp/release-notes.md

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7
        with:
          distribution: goreleaser
          version-file: .tool-versions
          args: release --release-notes=tmp/release-notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
