name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - uses: tooppoo/rellog-actions/setup@2abfca180ea8f95dc3d77be64b25b4bc33a0b380 # 0.1.0
        with:
          release-id: ${{ github.ref_name }}
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: 'go.mod'

      - name: check release is get ready or not
        run: rellog ready ${{ github.ref_name }}

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0

      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Check
        run: just ci

      - name: Save licenses
        run: just license-save

      - name: create VERSION file
        run: echo ${{ github.ref_name }} > VERSION

      # remove the version header, because GoReleaser will add it automatically.
      - name: create release note file as input
        run: |
          sed '/^## /d' .rellog/release-notes/${{ github.ref_name }}.md \
            > "${{ runner.temp }}/release-notes.md"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version-file: .tool-versions
          args: release --release-notes="${{ runner.temp }}/release-notes.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
